### ISSUE TITLE
Adding Subtitles removed audio

### ISSUE THREAD

**Issue by jainvasu631** [sheldonkwoodward/pymkv#44]
mkv = MKVFile()
lmkv.add_track(episode_path)
mkv.add_track(subtitle_path)
mkv.mux(output_path)
this causes the output_path to have no audio.

**Comment by sheldonkwoodward** [comment]
Hi @jainvasu631, I believe what you are trying to do is take an existing MKV file and add subtitles to it, let me know if that is not correct. But if that is the case, you should construct an MKFile using the episode file and then add the subtitle track to it. Something like this:

```python
mkv = MKVFile(file_path=episode_path)
mkv.add_track(subtitle_path)
mkv.mux(output_path)
```

**Comment by jainvasu631** [comment]
Thanks @sheldonkwoodward.  I was adding the audio seperately, however this fixed the problem.
